/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component.panelitems;

import com.raven.model.dao.ChiTietSachDAO;
import com.raven.model.dao.SachDAO;
import com.raven.model.modeldata.ChiTietSach;
import com.raven.model.modeldata.Sach;
import com.raven.swing.customswing.comboboxcustom.ComboBoxSuggestion;
import com.raven.swing.customswing.imageswing.ImageAvatar;
import com.raven.swing.table.EventAction;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.event.AncestorListener;

/**
 *
 * @author DELL
 */
public class BookSelected extends javax.swing.JPanel {

    private String idSach;

    public ImageAvatar getDeleteIA() {
        return this.lbDelete;
    }

    public ComboBoxSuggestion getComBoBoxID() {
        return this.comboBoxID;
    }

    public String getIdSach() {
        return idSach;
    }

    public BookSelected(ImageIcon icon, Sach s) {
        initComponents();
        if (icon != null) {
            lbIcon.setIcon(icon);
        };
        idSach = s.getIdSach();
        lbTenSach.setText(s.getTenSach());
        ChiTietSachDAO.getInstance().getCTSByIDSach(s.getIdSach()).forEach(cts -> {
            if (cts.getTrangThai().equalsIgnoreCase("Sẵn sàng")) {
                comboBoxID.addItem(cts.getIdChiTietSach());
            }
        });
        lbDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTenSach = new javax.swing.JLabel();
        comboBoxID = new com.raven.swing.customswing.comboboxcustom.ComboBoxSuggestion();
        lbDelete = new com.raven.swing.customswing.imageswing.ImageAvatar();
        lbIcon = new com.raven.swing.customswing.imageswing.ImageAvartaSquare();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        lbTenSach.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lbTenSach.setText("Tên sách");
        lbTenSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lbTenSach.setFocusable(false);

        comboBoxID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lbDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/remove_50px.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(153, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTenSach, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.customswing.comboboxcustom.ComboBoxSuggestion comboBoxID;
    private javax.swing.JSeparator jSeparator1;
    private com.raven.swing.customswing.imageswing.ImageAvatar lbDelete;
    private com.raven.swing.customswing.imageswing.ImageAvartaSquare lbIcon;
    private javax.swing.JLabel lbTenSach;
    // End of variables declaration//GEN-END:variables
}
