/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component.panelitems;

import com.raven.model.modeldata.Sach;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author DELL
 */
public class BookCard extends javax.swing.JPanel {

    public int soLuongSanSang;
    public int soLuong;

    public int getSoLuongSanSang() {
        return soLuongSanSang;
    }

    public BookCard() {
        initComponents();
    }

    public void showBook(ImageIcon icon, String tenSach, String theLoai, String tacGia, int soLuong) {
        if (icon != null) {
            pnIcon.setIcon(icon);
        }
        this.soLuong = soLuong;
        SimpleDateFormat sdf = new SimpleDateFormat("dd//MM/yyyy");
        jPanel1.setBackground(new Color(0, 0, 0, 0));
        lbTenSach.setText("<html><p style=\"width:140px\">" + tenSach + "</p></html>");
        lbViTri.setText("<html><p style=\"width:140px\">" + "Thể loại: " + theLoai + "</p></html>");
        lbTacGia.setText("<html><p style=\"width:140px\">" + "Tác giả: " + tacGia + "</p></html>");
        lbSoLuong.setText(lbSoLuong.getText() + soLuong);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    public void selected() {
        if (this.soLuongSanSang > 0) {
            setTextSoLuong(getSoLuongSanSang() - 1, this.soLuong);
        }
    }

    public void deSelected() {
        setTextSoLuong(getSoLuongSanSang() + 1, this.soLuong);
    }

    public void setTextSoLuong(int soLuongSanSang, int soLuong) {
        lbSoLuong.setText("Số lượng: " + soLuongSanSang + "/" + soLuong);
        this.soLuongSanSang = soLuongSanSang;
    }

    public void setViTri(String viTri) {
//        lbViTri.setText("");
        lbViTri.setText("Vị trí: " + viTri);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTenSach = new javax.swing.JLabel();
        lbTacGia = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbViTri = new javax.swing.JLabel();
        pnIcon = new com.raven.swing.customswing.imageswing.ImageAvartaSquare();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        lbTenSach.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbTenSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenSach.setText("Tên sách");

        lbTacGia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lbTacGia.setText("Tác giả: ");
        lbTacGia.setFocusable(false);

        lbSoLuong.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lbSoLuong.setText("Số lượng:");
        lbSoLuong.setFocusable(false);

        lbViTri.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lbViTri.setText("Vị trí: ");
        lbViTri.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbViTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnIcon.setBackground(new java.awt.Color(255, 255, 255));
        pnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/cc.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTacGia;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JLabel lbViTri;
    private com.raven.swing.customswing.imageswing.ImageAvartaSquare pnIcon;
    // End of variables declaration//GEN-END:variables
}
